//objeto quer armazena o alinhamento e a descrição
export const aligmentAndDescription=  {
    "Lawful Good" :"Um personagem ordeiro e bom age tipicamente com compaixão e sempre com honra e senso de dever. Porém, personagens ordeiros e bons vão se arrepender ao fazerem qualquer ação que acreditem conflitar com o seu código, mesmo que em prol do bem maior. Estes personagens incluem nobres cavaleiros, paladinos e muitos anões. Criaturas ordeiras e boas incluem dragões dourados.",
    
    "Lawful Neutral" :"Um personagem ordeiro e neutro tipicamente acredita fortemente no espírito das leis como a honra, a ordem, as regras e as tradições, mas geralmente seguem um código pessoal em adição a, ou mesmo preferindo a, algum código determinado por uma autoridade benevolente. Exemplos de personagens ordeiros e neutros incluem um soldado que sempre segue ordens, um juiz ou um oficial que adere impiedosamente à lei literal, e um monge disciplinado.",
    
    "Lawful Evil" :"Um personagem ordeiro e mau vê um sistema bem ordenado como sendo mais fácil de explorar do que de seguir. Exemplos deste alinhamento inclui tiranos, diabos, oficiais corruptos e mercenários que seguem um código de conduta restrito.",
    
    "Neutral Good" :"Um personagem neutro e bom age tipicamente de forma altruísta, sem se importar com os decretos de leis, regras comunitárias e tradições. Um personagem neutro e bom não vê problemas ao cooperar com os oficiais da lei, mas não se veem presos a eles. Caso a oportunidade de fazer o bem exija distorcer ou violar as regras, eles não sofrem o mesmo conflito interno que os personagens ordeiros e bons.",
    
    "True Neutral" :"Um personagem neutro (também chamado de “true neutral” ou neutro verdadeiro) é neutro nos dois extremos e não se sente fortemente inclinado a nenhum alinhamento e nem ativamente trabalha em prol do equilíbrio deles. Os druidas frequentemente seguem este caminho em prol do equilíbrio e, sob as regras do Advanced Dungeons & Dragons, era obrigatório que seguissem este alinhamento. No exemplo da 2ª Edição do Player’s Handbook, um druida típico poderia lutar contra um grupo de gnolls assassinos apenas para depois mudar de lado e salvar este mesmo grupo da extinção completa.",
    
    "Neutral Evil" :"Um personagem neutro e mal é egoísta e não possui nenhuma ressalva em se voltar contra seus aliados. Eles geralmente buscam aliados para avançar em seus objetivos pessoais. Um personagem neutro e mal não sente nenhuma culpa em ferir outras pessoas para conseguirem o que quer, mas não busca promover a carnificina ou destruição quando isso não lhe trouxer um benefício direto. Uma outra interpretação válida do neutro e mal é ver o mal como um ideal, espalhando o mal pelo mal, apenas para aumentar a influência do mesmo. Exemplos do primeiro tipo são ser um assassino que não se importa com as leis, mas não mata apenas por matar, um lacaio que planeja um golpe pelas costas de seu líder ou um mercenário que muda de lado ao receber uma oferta melhor. Um exemplo do segundo tipo seria um assassino mascarado que mata por matar só para causar medo e desconfiança na comunidade.",
    
    "Chaotic Good" :"Um personagem caótico e bom faz o que for necessário para mudar as coisas para melhor, desdenha as organizações burocráticas que impedem as melhorias sociais e valorizam demais a liberdade individual, não apenas para si mesmo, mas para todas as pessoas. Personagens caóticos e bons geralmente possuem boas intenções, mas seus métodos são desorganizados e, frequentemente, destoam do restante da sociedade.",
    
    "Chaotic Neutral" :"Um personagem caótico e neutro é um individualista que segue apenas a sua própria vontade e geralmente não se importa com as regras e nem com as tradições. Embora os personagens caóticos e neutros promovam os ideais de liberdade, é a sua liberdade individual que vem em primeiro lugar, bem e mal ficam em segundo plano em relação a sua necessidade de se sentirem livres.",
    
    "Chaotic Evil" :"Um personagem caótico e mal não respeita regras, a vida de terceiros ou qualquer coisa além de seus próprios desejos, que são geralmente egoístas e cruéis. Eles supervalorizam a liberdade individual, mas não se importam com as vidas ou com a liberdade de terceiros. Os personagens caóticos e maus não funcionam bem em grupos pois odeiam receber ordens e, geralmente, não se comportam bem a não ser que não tenham outra alternativa. Exemplos deste alinhamento incluem a maioria dos mortos-vivos mais poderosos, como os liches e os assassinos violentos que matam por prazer e não por ganho pessoal.",
}